#!/bin/bash
# Author: Tong Xing
# Stevens Institute of Technology 2020
set -e
DIR=$1
TARGET_MACHINE=$2
CHECKPOINT=$3
help()
{
    cat <<- EOF
Desc: restore.sh is for restore Hcontainer in remote machine
    - Container DIR is the directory store the Dockerfile to build a docker image
    - TARGET Machine is the target machine user@ip. example: popcorn@10.4.4.111
    - CHECKPOINT is the recoded dumped directory path generated by recode.sh
Example: ./popcorn.sh ./helloworld ubuntu@172.31.23.242 ./hcontainer_check
Author: Tong Xing
Stevens Institute of Technology 2020
EOF
    exit 0
}
while [ -n "$1" ];do
        case $1 in
                -h) help;; # function help is called
                --) shift;break;; # end of options
                -*) echo "error: no such option $1."; exit 1;;
                *) break;;
esac
done
if [ $# != 3 ]
then
    help
fi



ssh $TARGET_MACHINE "bash" < ./check.sh
RDIR=/tmp/h_container_remote
scp -r $DIR $TARGET_MACHINE:$RDIR >/dev/null 2>&1
WDIR=$(cat $DIR/Dockerfile | grep WORKDIR | awk '{print $2}' | sed -n '1p')
BIN=$(ls $DIR | grep aarch64) 
EXE=$(echo ${BIN%_*})

RCID=$(ssh $TARGET_MACHINE "bash -s" < ./builder.sh $RDIR)
scp -r $CHECKPOINT $TARGET_MACHINE:/tmp/ >/dev/null 2>&1
sudo rm -r $CHECKPOINT
ssh $TARGET_MACHINE "sudo mv /tmp/${CHECKPOINT##*/} /var/lib/docker/containers/$RCID/checkpoints/"


ssh $TARGET_MACHINE "sudo docker container start --checkpoint ${CHECKPOINT##*/} $RCID"
sleep 5 
echo docker show restore container $RCID is running
ssh $TARGET_MACHINE "sudo docker ps"

