# Use an official Python runtime as a parent image
FROM scratch

# Set the working directory to /app
WORKDIR /app

COPY . /app
# Copy the current directory contents into the container at /app

CMD ["./popcorn-hello"]

