# Use an official Python runtime as a parent image
FROM scratch

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

CMD ["./popcorn-hello"]

